
UPDATE_AMOUNTS_FOR_WATER_RESOURCES = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\updated amounts for correction_MatrixZ.xlsx"
INDEXES_PEF_ALLOCATION = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\indexes_PEF-phase 2-start_Allocation, cut-off.xlsx"
INDEXES_WATERBALANCE_CORRECTION = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\indexes_waterBalance_correction_20200326.xlsx"
DATASETS_TO_EXCLUDE_FROM_CONVERSION = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\datasets to exclude from amount conversion for water, Resources.xlsx"
WATER_AMOUNT_AND_UNIT_CORRECTION = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\water amount and unit correction_20200326.xlsx"
MATRIX_B_PICKLE = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles\B.pkl"
MATRIX_A_PICKLE = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles\A.pkl"
MATRIX_Z_PICKLE = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles\Z.pkl"
FLOW_CHANGES_SPEC = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\flow_changes_spec.xlsx"
PICKLES_SOURCE_DIRECTORY = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles"
EXCEL_SOURCE_DIRECTORY = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel"
EXCEL_DESTINATION_DIRECTORY = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\output\excels"
PROCESS_FILES_SOURCE_DIR = r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\00_ILCD_pilot_20190611\processes, LCI only"
PROCESS_FILES_Destination_DIR = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\output\process_files"
DATASET_LIST_FLOWCHANGES = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\datasetList_flowChange.xlsx"
